CURRENT ONGOING CASE:

[ x ] Once a doctor recruits a patient, the patient should be added to the doctors list of patients
        - code_location: @ /countries/insert_countries

[ x ] Upon going to "My Patients" link, a doctor should be able to start a new consultation by 
        clicking on "start a new consultation".
        The doctor_id and the client_id should be used to create a new consultation 
        and the page should redirect to the newly created consultation.
        - code_location: @ /countries/insert_countries

[ ] ABENGUA must be completed for at least 1 person
        - code_location: @ /countries/insert_countries

[ ] Work on the doctors recruiting patients feature and 
        use Abengua people as an example test case, you must have proper emails.

[ ] Add abifio style ordering - i.e. patient should be able to post labtests 
        or prescriptions on the platform for service providers to accept
        and provide the service.

[ ] Update the UI with more information like the Michigan People's page.

[ ] Complete the Nurses menu and finish all use-cases about nurses

[ ] What happens to past / expired appointments or completed appointments ?

[ ] Create user guide tutorials to show users how to navigate the site
        this will be created as a separate app/use case
        and the links will redirect to Youtube,etc for the users to follow.

[ ]  Create the suggestion box app and add it so users can send suggestions.

3. Be able to request labs for a patient and be able to upload results onto the system
    for review by a doctor and by the patient.
    
4.  THEN ADD THE REFERRAL SYSTEM and see if docs will start using it.



############################################################################



[x] -- User should be able to register and automatically get assigned to a user type/group 
        - code_location: @ /countries/insert_countries
        
[x] -- a patient can register and login
[x] -- a patient can book their own appointment with a doctor.
        (When the appointment is confirmed then the consultation is created on the app)
[x] -- a doctor should be able to confirm an appointment and hence a signal 
            will create a fresh consultation sheet.

[x] -- DO ALL THE SUPERMED LOGIC and try an online booking and full consultation.

[x] -- Make all the lab_results templates to work as simple CRUD first

[x] -- Ensure that once a lab is requested the Template is created in the data base.

[x] -- Also Ensure that the Universal_Lab_Results Template should always be created for 
        every lab request so that just in case there is no template it can be used.

[x] -- Doctors should be able to recruit patients for the "Health Tracker Program"

[x] -- System sends annual emails to remind patients of their annual health screening
        and asks the patient to confirm so that the lab_request will be generated.
        Use cron jobs

[ ] -- Create confirmation Link on africahealthonline so patients can click to generate their
        lab requests

[ ] -- When lab_requests are generated it is also posted as opportunities for Service providers
        to accept/respond to.

[ ] -- Add user reading info on the homepage - just like the university of Michigan
                e-health platform. Plus a little bit of "about us", etc

[ x ] - Give the autogenerated bookma Numbers so doctors can give to other people.

[ x ] Ensure that doctors setup their appointment settings upon registering
        by redirecting them to the appointments_settings page.

[ x ] - Add link to registration page to allow doctors and other health professionals
        to create their profiles using https://www.twibbonize.com
        - this was added as a link in the various menu partials

        

CURRENTLY WORKING ON....

5. [ ] -- Learn whatsapp api and integrate at point of appointments booking time and 
        at time of confirmation.

6. [ x ] -- DO PHR Functionality so patients can track some health parameters 
                          -- Almost done but i need to add the lab results forms for entering 
                                and also a display format for the results.

PROBLEMS FACED NOW : Patient is unable to fully book an appoinment for doctor to confirm - 
This needs fixing.

7. Patient should be able to go to MY HEALTH DATA and see links to all his/her labs, scans and vitals.

-- patient should be able to view his vital signs History
-- patient should be able to add vitals signs records

Learn how to send whatsapp messages from the app.

Doctor should be able to register a patient so you the doctor 
is now the patient's primary physician.

[ x ] ---- Patient should be able to select their primary doctor


[ x ] - A patient should be able to just go to a list of doctors and just book an appointment 
with a chosen doctor.



[ x ] i.e. If appointment settings is not set - exclude the name from the professional 
    from the drop down.

[ x ] Always redirect to the appointment settings page upon login with a message -
    if the appointment settings is not done.

[ x ] How to send patients reminders for their annual checkup labs ??? - done using cron jobs in cpanel